# Generated by Django 4.0.3 on 2022-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=15, verbose_name='Buyer GSTIN')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Amt. with GST')),
                ('created', models.DateField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
