# Generated by Django 4.0.3 on 2022-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0004_alter_entry_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amt. with GST'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gst_percent',
            field=models.IntegerField(choices=[(5, 'Two'), (12, 'Three'), (18, 'Four'), (28, 'Five')], default=18, verbose_name='GST Slab'),
        ),
    ]
