# Generated by Django 4.0.3 on 2022-03-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0006_entry_delayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='delayed',
        ),
    ]
