# Generated by Django 4.0.3 on 2022-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0009_othertaxes_accountant_alter_othertaxes_tax_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertaxes',
            name='tax_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
