# Generated by Django 4.0.3 on 2022-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0011_alter_othertaxes_tax_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sale_item',
            field=models.CharField(max_length=100, null=True, verbose_name='Sale Item'),
        ),
    ]
