# Generated by Django 4.0.3 on 2022-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0012_entry_sale_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sale_item',
            field=models.CharField(default='Goods', max_length=100, verbose_name='Sale Item'),
        ),
    ]
