# Generated by Django 4.0.3 on 2022-03-23 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gstrepayment', '0014_alter_othertaxes_options_rename_paid_entry_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_due',
        ),
        migrations.RemoveField(
            model_name='othertaxes',
            name='is_due',
        ),
        migrations.AddField(
            model_name='entry',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='othertaxes',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 0, 0, tzinfo=utc)),
        ),
    ]
